### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by amiltonwong** [pqhieu/jsis3d#1]
Hi, @pqhieu ,

After running `python train.py --config configs/s3dis.json --logdir logs/s3dis`, I got the following error. I had downloaded S3DIS dataset (h5 format) and have it extracted in `JSIS3D/data/s3dis/h5` as `JSIS3D/data/s3dis/h5/s3dis_h5_07042019/*.h5`

```
python train.py --config configs/s3dis.json --logdir logs/s3dis
/root/anaconda3/envs/tf1.3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "train.py", line 31, in <module>
    dataset = S3DIS(args['root'], training=True)
  File "/data/code9/JSIS3D/loaders/s3dis.py", line 19, in __init__
    self.coords.append(fin['coords'][:])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/root/anaconda3/envs/tf1.3/lib/python3.6/site-packages/h5py/_hl/group.py", line 167, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'coords' doesn't exist)"

```

It seems some error in h5py reading. Could you suggest me how to fix such issue?

THX!

```
Here are my package configurations:
h5py == 2.7.1
hdf5==1.10.1
pytorch == 0.4.0
```

**Comment by amiltonwong** [comment]
Fixed it. 
Just move those h5 files into JSIS3D/data/s3dis/h5  :P

**Comment by longmalongma** [comment]
> Hi, @pqhieu ,
> 
> After running `python train.py --config configs/s3dis.json --logdir logs/s3dis`, I got the following error. I had downloaded S3DIS dataset (h5 format) and have it extracted in `JSIS3D/data/s3dis/h5` as `JSIS3D/data/s3dis/h5/s3dis_h5_07042019/*.h5`
> 
> ```
> python train.py --config configs/s3dis.json --logdir logs/s3dis
> /root/anaconda3/envs/tf1.3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
>   from ._conv import register_converters as _register_converters
> Traceback (most recent call last):
>   File "train.py", line 31, in <module>
>     dataset = S3DIS(args['root'], training=True)
>   File "/data/code9/JSIS3D/loaders/s3dis.py", line 19, in __init__
>     self.coords.append(fin['coords'][:])
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "/root/anaconda3/envs/tf1.3/lib/python3.6/site-packages/h5py/_hl/group.py", line 167, in __getitem__
>     oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "h5py/h5o.pyx", line 190, in h5py.h5o.open
> KeyError: "Unable to open object (object 'coords' doesn't exist)"
> ```
> 
> It seems some error in h5py reading. Could you suggest me how to fix such issue?
> 
> THX!
> 
> ```
> Here are my package configurations:
> h5py == 2.7.1
> hdf5==1.10.1
> pytorch == 0.4.0
> ```



> JSIS3D/data/s3dis/h5/s3dis_h5_07042019/*.h5

JSIS3D/data/s3dis/h5/s3dis_h5_07042019/*.h5

> Hi, @pqhieu ,
> 
> After running `python train.py --config configs/s3dis.json --logdir logs/s3dis`, I got the following error. I had downloaded S3DIS dataset (h5 format) and have it extracted in `JSIS3D/data/s3dis/h5` as `JSIS3D/data/s3dis/h5/s3dis_h5_07042019/*.h5`
> 
> ```
> python train.py --config configs/s3dis.json --logdir logs/s3dis
> /root/anaconda3/envs/tf1.3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
>   from ._conv import register_converters as _register_converters
> Traceback (most recent call last):
>   File "train.py", line 31, in <module>
>     dataset = S3DIS(args['root'], training=True)
>   File "/data/code9/JSIS3D/loaders/s3dis.py", line 19, in __init__
>     self.coords.append(fin['coords'][:])
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "/root/anaconda3/envs/tf1.3/lib/python3.6/site-packages/h5py/_hl/group.py", line 167, in __getitem__
>     oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "h5py/h5o.pyx", line 190, in h5py.h5o.open
> KeyError: "Unable to open object (object 'coords' doesn't exist)"
> ```
> 
> It seems some error in h5py reading. Could you suggest me how to fix such issue?
> 
> THX!
> 
> ```
> Here are my package configurations:
> h5py == 2.7.1
> hdf5==1.10.1
> pytorch == 0.4.0
> ```

Hello,I meet same problem,my dataset path is that: JSIS3D/data/s3dis/h5/*.h5. do you solve this problem?
