### ISSUE TITLE
How to prepare my own data set

### ISSUE THREAD

**Issue by zhangmenghan** [pqhieu/jsis3d#12]
In your code, you say follow the scripts folder to learn how to prepare the data set.But there are four files in the folder, what steps should be followed to prepare.
Also, how do I set the num_points parameter when I do the prepare_h5.py file:
`batch = room_to_blocks(fname, **num_points,** size=1.0, stride=0.5)`
I would also like to ask which of the following data sets is appropriate for processing
Stanford3dDataset_v1.2_Aligned_Version  or  Stanford3dDataset_v1.2

**Comment by pqhieu** [comment]
Assume that you use the aligned version, you only need to run `collect_annotations.py` and then `prepare_h5.py` to prepare the data, the others are standalone scripts to calculate some dataset statistics. `num_points` is set to 4096 in my experiments.

**Comment by zhangmenghan** [comment]
Thanks a lot, I will try it now to prepare my dataset
