### ISSUE TITLE
about plot.py

### ISSUE THREAD

**Issue by zhangmenghan** [pqhieu/jsis3d#13]
Hello, I want to execute plot.py to check the result, and the parameter "metric" has reported an error. I would like to ask you what the parameter "metric" means and what the default value you set is.
Thank you.

**Comment by pqhieu** [comment]
The `--metric` flag is to determine which metric you want to plot. Possible values are `accuracy`, `IoU`, `precision`, and `recall`.

**Comment by zhangmenghan** [comment]
I would also like to ask you about how you did the visualization after the segmentation of the scene, thank you

**Comment by pqhieu** [comment]
I use my inhouse visualizer. There's a visualization flag in `eval.py`, you can use that to save the point clouds to .ply files and use MeshLab to view. However, you need to implement color mapping before saving to see semantic/instance segmentation.

**Comment by zhangmenghan** [comment]
Thank you for your reply very much

**Comment by longmalongma** [comment]
> color mapping

Hello,how to implement color mapping before saving to see semantic segmentation?have you implemented color mapping in your code?

**Comment by longmalongma** [comment]
> Thank you for your reply very much

Hello,do you implement color mapping?can you provide code about color mapping?looking forward your reply.
