### ISSUE TITLE
how to visualize the experiment results of sematic segmentation on s3dis dataset?

### ISSUE THREAD

**Issue by longmalongma** [pqhieu/jsis3d#14]
Hello, how to visualize the experiment results of semantic segmentation on s3dis dataset?Do you ｕｐload ｔｈｅ code about visualization of semantic segmentation on s3dis dataset?looking forward your reply.

**Comment by pqhieu** [comment]
Please refer to #13.

**Comment by longmalongma** [comment]
> Please refer to #13.

Hello,how to implement color mapping before saving to see semantic segmentation?have you implemented color mapping in your code?

**Comment by pqhieu** [comment]
You can replace this [line](https://github.com/pqhieu/jsis3d/blob/4c4105527286bb9a8c10483b9e38580fc7a51e00/eval.py#L106) with your own colors based on semantic/instance labels. I didn't include the code for color mapping in this repo.

**Comment by longmalongma** [comment]
> You can replace this [line](https://github.com/pqhieu/jsis3d/blob/4c4105527286bb9a8c10483b9e38580fc7a51e00/eval.py#L106) with your own colors based on semantic/instance labels. I didn't include the code for color mapping in this repo.

I see,thanks for your reply.when I try to run pred.py,I met this problem,
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=405 error=11 : invalid argument
my pytorch gpu environment is ok, I have no idea ｗhat is wrong?

**Comment by pqhieu** [comment]
Sorry, I can't help you with environment related issues.
Quick Google search gives the following [dicussion](https://github.com/pytorch/pytorch/issues/15797).

**Comment by longmalongma** [comment]
> Sorry, I can't help you with environment related issues.
> Quick Google search gives the following [dicussion](https://github.com/pytorch/pytorch/issues/15797)ii

> Sorry, I can't help you with environment related issues.
> Quick Google search gives the following [dicussion](https://github.com/pytorch/pytorch/issues/15797).

do your pred.py use torch-cpu version not torch-gpu version?my computer only has installed torch-gpu.in other words,if i want to run your pred.py,i must install torch-cpu version?

**Comment by pqhieu** [comment]
It uses GPU for prediction. If you install torch-gpu then you already have the cpu version, as far as I understand.

**Comment by longmalongma** [comment]
I see,thanks for your reply again.



------------------ 原始邮件 ------------------
发件人: "Quang-Hieu Pham"<notifications@github.com>;
发送时间: 2019年10月3日(星期四) 中午11:27
收件人: "pqhieu/jsis3d"<jsis3d@noreply.github.com>;
抄送: "longma"<1442342449@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [pqhieu/jsis3d] how to visualize the experiment results ofsematic segmentation on s3dis dataset? (#14)




It uses GPU for prediction. If you install torch-gpu then you already have the cpu version, as far as I understand.
