### ISSUE TITLE
KeyError: "Unable to open object (object 'coords' doesn't exist)"

### ISSUE THREAD

**Issue by longmalongma** [pqhieu/jsis3d#15]
Hello,I meet a problem,
KeyError: "Unable to open object (object 'coords' doesn't exist)"

my dataset path is that: JSIS3D/data/s3dis/h5/*.h5. can you tell me how to solve this problem?looking forward to your reply.

**Comment by pqhieu** [comment]
Please make sure that your data is not corrupted.
In addition, you can modify the `loaders/s3dis.py` file to see which file is causing the problem.

**Comment by longmalongma** [comment]
> Please make sure that your data is not corrupted.
> In addition, you can modify the `loaders/s3dis.py` file to see which file is causing the problem.

I see,thanks for your reply.

**Comment by bukeyan4318** [comment]
@longmalongma hello,I have the same problem as you. How did you solve it? We look forward to your reply. Thank you in advance.
