### ISSUE TITLE
coords and points

### ISSUE THREAD

**Issue by LiDaiY** [pqhieu/jsis3d#18]
Hello,
I am confused about the 'coords' and 'points'. I thought 'points' contain the XYZ, RGB and Normal. But I don't konw what does 'coords' represent. Looking forward your reply.

**Comment by pqhieu** [comment]
Hi @LiDaiY,

`coords` are the global coordinates of a scene, while `points` are the normalized coordinates in a block (in the range of [0, 1]). Later the method merges all of the blocks in a scene together for the MV-CRF step, hence it needs the global coordinates.

**Comment by LiDaiY** [comment]
Thanks for your reply.  I found data preprocessing scripts are in 'scripts' folders. I think I should read these codes for better understanding the data.
