### ISSUE TITLE
did anyone try this network with a custom dataset ? 

### ISSUE THREAD

**Issue by jediofgever** [pqhieu/jsis3d#20]
Hi there , 
thanks for the great open source contribution. I was wondering how is the network performing in a say custom dataset, is there anyone out there tried this ? 

thanks

**Comment by pqhieu** [comment]
Hi,

Thanks for your interest. Can you give more information about your problem/dataset?

**Comment by ZJU-PLP** [comment]
> Hi,
> 
> Thanks for your interest. Can you give more information about your problem/dataset?

Could you mind sharing the code creating s3dis_h5_07042019 dataset? I find that it's different from the pointnet++ version.

**Comment by pqhieu** [comment]
You can find them in the `scripts` folder.

**Comment by ZJU-PLP** [comment]
> You can find them in the `scripts` folder.

ok,tks!
