### ISSUE TITLE
On the visualization of prediction results

### ISSUE THREAD

**Issue by Noahjianlong** [pqhieu/jsis3d#21]
Hello, I predicted two files, semantics.npy and instances.npy when I reproduced your code.What is their viewing mode?3d point cloud or picture?

**Comment by pqhieu** [comment]
Please check the `eval.py` file for visualization. The default is to output point clouds into .ply files.

**Comment by Noahjianlong** [comment]
> Please check the `eval.py` file for visualization. The default is to output point clouds into .ply files.

Thank you very much for your reply. I output the format file you said that .ply files.However, from this point cloud information, I could not see the annotation information of semantic segmentation and instance segmentation, instead, it was like a point cloud with RGB information added.

**Comment by pqhieu** [comment]
Please refer to the following issue #14.

**Comment by Noahjianlong** [comment]
> Please refer to the following issue #14.

Ok, thanks for your prompt reply. I have one more question.When I tried to make my own h5 data set to test as a test set, I found that the original data set had not only the point cloud file of the whole room, but also the part data set.As a test set, is it also a point cloud file that requires part data set?If the component data set has been collected in advance, what is the use of semantic segmentation?

**Comment by pqhieu** [comment]
I'm not sure that I understand your question correctly. But if the part dataset that you mentioned are the small 1x1x1 blocks, then it is required. The instance labels only discriminate between different objects in the scene, not their "semantic" (categorical) information. In short, with instance labels, you only know this part is an object, not what object it is. So you need both of them to evaluate your final results.

**Comment by Noahjianlong** [comment]
![1581170896(1)](https://user-images.githubusercontent.com/49674430/74087198-eb4da080-4ac4-11ea-9748-1caf90cdde14.jpg)
Sorry, I did not express clearly, I referred to your previous hint and still have two questions. The first question is how to distinguish the generated semantic and instance tags?I reproduced your model and visualized the generated.ply file, as shown in the figure above, but only the information of the instance label can be seen for different colors. How can the semantic segmentation label be reflected?

**Comment by Noahjianlong** [comment]
![1581170896(1)](https://user-images.githubusercontent.com/49674430/74087566-901dad00-4ac8-11ea-9bd7-62232e52584c.jpg)

**Comment by Noahjianlong** [comment]
![1581174874(1)](https://user-images.githubusercontent.com/49674430/74087613-fc001580-4ac8-11ea-9ce7-81f2c6d34ce1.jpg)
![1581174879(1)](https://user-images.githubusercontent.com/49674430/74087617-03bfba00-4ac9-11ea-9815-c68371577261.jpg)
The second problem is about making my own test set. I collected my own point cloud files with lidar and intend to make H5 data set for testing. But the production process failed. Analyze the reason. Can I not collect the component data set of point cloud like the original data set? As shown in the file above.I'm looking forward to your reply.

**Comment by Noahjianlong** [comment]
![1581170896(1)](https://user-images.githubusercontent.com/49674430/74087631-4bdedc80-4ac9-11ea-95bf-b0e2b1caaf68.jpg)

**Comment by Noahjianlong** [comment]
This is the picture of the first question I added.
