### ISSUE TITLE
Training and Inference

### ISSUE THREAD

**Issue by abhigoku10** [pqhieu/jsis3d#23]
@pqhieu thanks for open sourcing the wonderfull work , i had few queries
Q1 have you trained the architecture on the available other dataset like semanttic Kitti and 3D dataset
Q2 If not trained can we follow the same training pipeline , if trained can you please share the pre-trained model
Q3 can we use the currently pre-trained model to test on custom dataset which less number of point cloud density

Thanks in advance

**Comment by pqhieu** [comment]
Hi @abhigoku10,

Thanks for your interest in the paper. To answer your questions:
1. No I haven't trained the architecture on other datasets except from S3DIS and SceneNN.
2. You can absolutely use the same training pipeline for SemanticKITTI or other dataset.
3. I would advise you to test on your custom dataset first, and then to finetune the model to see if there is any improvement.
