### ISSUE TITLE
About preparing my own dataset

### ISSUE THREAD

**Issue by lin1061991611** [pqhieu/jsis3d#24]
hello，i am confued about the blocks in room_to_blocks in prepare_h5.py , what should i set up the threshold , and how dose cells work?

**Comment by pqhieu** [comment]
So usually a room will be split into different blocks, where each block is determined by `size`, with `stride` is the distance between one block to the next. The threshold depends on how dense your point cloud is and the maximum number of points in your training (in this case it is 4096).

Hope this helps.
