### ISSUE TITLE
step size when training

### ISSUE THREAD

**Issue by AlexSeongJu-sr** [pqhieu/jsis3d#25]
Hi. 

Firstly, I appreciate for your great work and sharing your code.

Currently, I'm using your model for my project and I have a question.

On your thesis, it says that you set your decay rate to 0.5 and it applies for every 50 epochs.

However, in the config.json file, the step size is set to 20, not 50. 

Which one is the right value? thank you

**Comment by pqhieu** [comment]
You can use the same step size as in the config file. Originally we set the value to 50 but found that 20 works the same.
