### ISSUE TITLE
About the input channel of data

### ISSUE THREAD

**Issue by yanghu819** [pqhieu/jsis3d#27]
The costom data of pointcloud is 3 dimensions， why is this data 9 dimensions， thank you very much for checking my issue

**Comment by pqhieu** [comment]
We also include the RGB values and normalized coordinates for each point, so that's why the data has 9 channels.

**Comment by yanghu819** [comment]
Thank you，the first three channels are for xyz coordinates？

Quang-Hieu Pham <notifications@github.com> 于2020年9月13日周日 下午5:51写道：

**Comment by pqhieu** [comment]
Yes, you can take a look at this [line](https://github.com/pqhieu/jsis3d/blob/b6b8aaecf120e9e80910f897b50094885ef7e307/scripts/prepare_h5.py#L52) onwards to understand the format.

**Comment by yanghu819** [comment]
thank you very much

Quang-Hieu Pham <notifications@github.com> 于2020年9月14日周一 下午9:54写道：
