### ISSUE TITLE
How to calculate the mAP?

### ISSUE THREAD

**Issue by tpzou** [pqhieu/jsis3d#28]
I find there is no score and only one pair of RP, so how to calculate the mAP?

**Comment by pqhieu** [comment]
We use the same AP as defined in the COCO dataset, which means we change the IoU threshold from 0.5 to 0.95 with 0.05 step size and calculate precision at these intervals.mAP is the average of all the classes.

**Comment by tpzou** [comment]
Thanks for your reply.
But I stll don't understand how to calculate a single AP.  I don't know if I've made my point clear.  I mean that if I set the IoU as 0.5,  as far as I am concerned, the AP is to calculate the area under the PR polyline. But in this work, there is no score, and it only has one pair of PR. So how to calculate to area?

**Comment by pqhieu** [comment]
You calculate the precision at several IoU threshold and take the average. I suggest that you take a look at this article https://jonathan-hui.medium.com/map-mean-average-precision-for-object-detection-45c121a31173

**Comment by haffybra** [comment]
@pqhieu I had the same doubts on how to calculate the AUC. Check this repository, it might help 
[https://github.com/rafaelpadilla/review_object_detection_metrics](https://github.com/rafaelpadilla/review_object_detection_metrics)
