### ISSUE TITLE
sceneNN

### ISSUE THREAD

**Issue by lllmmmwww** [pqhieu/jsis3d#30]
Thank you for your contribution!I have a question. 
If I use a dataset like sence NN, Do I need to turn room into block in prepareh5. py？

**Comment by QingWindIsStillTheWind** [comment]
Have you solved this problem now

**Comment by pqhieu** [comment]
> Thank you for your contribution!I have a question.
> If I use a dataset like sence NN, Do I need to turn room into block in prepareh5. py？

Yes. You can download the ply files from SceneNN, extract the point clouds and run through preprocessing.
