### ISSUE TITLE
Cannot reproduce paper results

### ISSUE THREAD

**Issue by zhangguanghui1** [pqhieu/jsis3d#7]
I run your code according to the current Readme file **with MV-CRF**. I use the same configuration present in s3dis.json but I cannot obtain the same results evidenced in the paper.
The platform: python 3.5.2,  torch 1.0, cuda 9.0 cudnn 7.3.0
After 100 epoch, 
> Overall accuracy: 0.829
> Mean accuracy: 0.507
> Mean IoU: 0.433
> Mean precision: 0.389
> Mean recall: 0.287

Can you help me? Thank you very much.

**Comment by pqhieu** [comment]
Hi @zhangguanghui1,

Sorry for the late reply. I was away so I couldn't look into your issue.
As I said before in #3, you can get results that are similar to the paper if you log an earlier model (around 40 epochs). I have changed the default training config accordingly to clear any confusion.

**Comment by HaiyongJiang** [comment]
Hi @zhangguanghui1, do you resolve the problem? I also got similar performance as yours. Do you have any suggestion to improve it? Thank you.
