### ISSUE TITLE
mvcrf issue

### ISSUE THREAD

**Issue by FrankCAN** [pqhieu/jsis3d#9]
Hi, can I directly use your mvcrf code just for segmentation, without instance? Many thanks.

Best Regards
Frank

**Comment by pqhieu** [comment]
If you have instance prediction then there will be no issue. If not then you can check out [DenseCRF](https://arxiv.org/abs/1210.5644) code for segmentation only.

**Comment by pqhieu** [comment]
Close due to inactivity.
